### PR TITLE
GitHub provider implementation: Authenticate and Search Principals

### PR DESCRIPTION
**Pull request by prachidamle**
Provider implementation to authenticate and search on github

Also added an endpoint to list supported provider configs - currently with default values

@cjellick @ibuildthecloud

### CODE REVIEW

**Comment by vincent99** [comment]
For configuring this, I'd really like to be able to go back to one click that sets the token/config and brings up the popup OAuth window.  The way it is now with separate save & test buttons is really bad UX.

The gotcha is that opening the popup has to be in direct (not asynchonous) response to the user event (of clicking the button).  I can't make an ajax call to configure and then go to the oauth URL.  The old code did the popup immediately (to a URL the UI constructed) and did the config post in the background.  But that requires the UI to know the URL, and hope that the post worked.

We also never addressed a method for testing providers like GitHub/SAML on edit that require redirects/async user interaction.

So proposed: A test method that can save the config (separate from the live config), then optionally send a HTTP redirect in the response.  The UI would then post the config to a new window (which is synchronous and so won't be popup blocked) and the auth response would contain the redirect to the github page.

**Comment by prachidamle** [comment]
@vincent99 Yes +1 to have one click save and test actions - currently havjng two different requests opens up the possibility of some issues in HA multinode cluster where teo requests might land up on different nodes.

**Comment by prachidamle** [comment]
@vincent99 question on the proposed:
- You mentioned about a separate save test config, that would return you redirect URL - this is the github url right?
- After following this redirect, UI will get a code, and then do POST /v3/tokens?action=testLogin?
- If this works, we do similar interaction to actually save the cofig and create token/account?

**Comment by vincent99** [comment]
Yes, post to set the Test config and redirect if appropriate for the driver.

For some drivers you need the new user context from the result of the test and the way it works indirectly by looking at the token is weird now.  So the whole thing could be combined into  one step for LDAP/etc like `testAndUpdateConfig`, with a separate `confirmTest` call for ones that require 2 steps (GitHub).

Direct PUT on the config resource should still be allowed for API users to manipulate the config without having to do interactive testing.

And there's still the issues with switching from one kind of auth to another to consider, though some of them should be better now with edit capability and users having an array of principal IDs instead of a single externalId.

**Comment by prachidamle** [comment]
@vincent99 With one action "testAndUpdateConfig", we basically are going to test if the config works and if it does then save it to the live config - without really checking back with user - is that ok? So only way for user to revert back is disable auth and start over? With this model, we are moving away from "save config with auth disbaled - then test login - then do final save with auth enabled", right?
Auth will be on once 'testAndUpdateConfig' returns success.

Also, I guess we might still not eliminate the possibility of 2 requests (testAndUpdateConfig and confirmTest ) to land up on different nodes in HA?

**Comment by cjellick** [comment]
LGTM

**Pull request merged**
